### PR TITLE
Fixed build

### LINKED ISSUE #277: SonataDatagridBundle 2.2.1 make tests fail.
The release of the 2.2.1 version of SonataDatagridBundle, 6 days ago, makes tests fail.

Example on Travis: https://travis-ci.org/sonata-project/SonataClassificationBundle/builds/201959001

@greg0ire I think it's your [commit (PR #45) on SonataDatagridBundle](https://github.com/sonata-project/SonataDatagridBundle/pull/45) that makes tests fail.

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targetting this branch, because I am only changing tests.

Closes #277 

## Subject

Datagrid bundle implements getRootAliases which is not mocked on other bundles, so it makes build fail. This PR fixes this.

### CODE REVIEW

File: Tests/Entity/CategoryManagerTest.php [hunk 1]
```diff
@@ -21,6 +21,7 @@ public function testGetPager()
         $self = $this;
         $this
             ->getCategoryManager(function ($qb) use ($self) {
+                $qb->expects($self->once())->method('getRootAliases')->will($self->returnValue(array()));
```
Comment (jlamur) [inline Tests/Entity/CategoryManagerTest.php]: `$qb->expects($self->any())->method('getRootAliases')->will($self->returnValue(array()));` to make it build on `--prefer-lowest` :)

Comment (greg0ire) [inline Tests/Entity/CategoryManagerTest.php]: Good catch @jlamur !

Comment (jordisala1991) [inline Tests/Entity/CategoryManagerTest.php]: I changed to ^2.2.1 on composer.json

Comment (greg0ire) [inline Tests/Entity/CategoryManagerTest.php]: That's even better!

**Comment by jordisala1991** [comment]
Now it works!

**Comment by greg0ire** [comment]
Thanks @jordisala1991 !
