### PR TITLE
Remove form field type deprecations

### LINKED ISSUE #314: Accessing type "xxx" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.20.1          The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2           Symfony SonataBlockBundle
sonata-project/cache                     1.0.7           Cache library
sonata-project/classification-bundle     3.x-dev 193363c Symfony SonataClassificationBundle
sonata-project/core-bundle               3.4.0           Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1           Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2           Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.x-dev 268a200 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0           Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1           Lightweight Exporter library
sonata-project/intl-bundle               2.3.1           Symfony SonataIntlBundle
sonata-project/media-bundle              3.x-dev d7c4934 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0           Symfony SonataNotificationBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.2  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/polyfill-apcu      v1.4.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.4.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.4.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.4.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.4.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.25 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.21 (cli) (built: Jul  8 2017 07:40:05) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.21, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject
I'm currently updating my project and removing all deprecations I see to update from Symfony 2.8 to 3.0. Current SonataClassificationBundle has its admin classes forms created with string type for the fields. For example in `Sonata\ClassificationBundle\Admin\CategoryAdmin`:

```
class CategoryAdmin extends ContextAwareAdmin
{
    ...
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->with('General', array('class' => 'col-md-6'))
                ->add('name')
                ->add('description', **'textarea'**, array(
                    'required' => false,
                ))
        ;
    }
    ...
}
```

This raises a deprecation warning explaining that this will not be supported in Symfony 3.0 and above.

## Steps to reproduce
Use SonataClassificationBundle with Symfony 2.8.x.

## Expected results
No deprecation warnings when a form for a SonataClassificationBundle entity is used in SonataAdmin.

## Actual results
A deprecation warning for each field in the form:

Accessing type "xxx" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\XxxxxxType" instead.

### PR DESCRIPTION
**Pull request by enekochan**
I am targeting this branch, because it removes deprecations and it's BC.

Closes #314

## Changelog

```markdown
### Changed
- Changed string type declaration of form fields to the fully-qualified type class name.
```

## Subject

Remove deprecation warnings on form type fields to use the fully-qualified type class name of them.

### CODE REVIEW

File: Admin/CategoryAdmin.php [hunk 1]
```diff
@@ -60,15 +64,15 @@ protected function configureFormFields(FormMapper $formMapper)
         $formMapper
             ->with('General', array('class' => 'col-md-6'))
                 ->add('name')
-                ->add('description', 'textarea', array(
+                ->add('description', TextareaType::class, array(
```
Comment (greg0ire) [inline Admin/CategoryAdmin.php]: It's not that simple, this has to stay 2.3-compatible. See other bundles for making this conditional.

Comment (enekochan) [inline Admin/CategoryAdmin.php]: Can you point me to a bundle that does this, I can't find any. Thanks.

**Comment by greg0ire** [comment]
https://github.com/sonata-project/SonataAdminBundle/search?utf8=%E2%9C%93&q=TextType&type=

**Comment by enekochan** [comment]
Great, that was the solution I had in mind but wasn't sure it was the best one. I'll change the PR ASAP.

**Comment by greg0ire** [comment]
Please fix StyleCI though

**Comment by greg0ire** [comment]
#316 should fix Travis

**Comment by greg0ire** [comment]
Restarting the build

**Comment by greg0ire** [comment]
Green! @sonata-project/contributors please review!

**Comment by core23** [comment]
Thanks @enekochan

**Comment by enekochan** [comment]
Glad I could contribute :)
