### PR TITLE
Fix conflict of datagrid context value and persistent parameter

### LINKED ISSUE #286: Datagrid filter conflicts with context parameter
## Subject

Datagrid filter conflicts with context parameter.

## Steps to reproduce

For example we have 2 contexts: `default` and `context`.

When first entering the categories in the admin panel, the uri looks like:
`tree?hide_context=0`

We can switch contexts in categories context custom switcher

If we switch to `default` context, the uri will look like this:
`tree?context=default&hide_context=0`

And the datagrid filter will appear with the selected context:

If we select `context` context in datagrid filter and press "Filter", we will have uri:
`
list?filter[context][type]=&filter[context][value]=context&filter[name][type]=&filter[name][value]=&filter[enabled][type]=&filter[enabled][value]=&filter[_page]=1&filter[_sort_by]=id&filter[_sort_order]=ASC&filter[_per_page]=32&context=default&hide_context=0
`

Now we have `filter[context][value]=context` from the selected filter and `context=default`, which priority is higher.

## Expected results

We are in a tree mode with selected `context` context.

## Actual results

We are in a list mode with selected `default` context. Does not matter what is in the uri param `filter[context][value]`, filter will be set to `default` context, which is defined in `context=default` parameter. 
Now we can try to change context in datagrid filter, but it would be locked on `default` because of 
`context=default` parameter. 

If we remove `context=default` from uri, datagrid filter will work fine.

## Checked on
- last 3.x version and datagrid bundle 2.2.1
- 3.2.0 version and datagrid bundle 2.2.0

### PR DESCRIPTION
**Pull request by ZRazor**
I am targeting this branch, because it is BC.

Closes #286

## Changelog

```markdown
### Fixed
- Fixed conflict of datagrid `context` value and persistent `context` parameter
```

### CODE REVIEW

File: Controller/CategoryAdminController.php [hunk 1]
```diff
@@ -40,8 +40,13 @@ public function listAction(Request $request = null)
         }
 
         $datagrid = $this->admin->getDatagrid();
+        $datagridValues = $datagrid->getValues();
 
-        if ($this->admin->getPersistentParameter('context')) {
+        $datagridContextIsNotSet = array_key_exists('context', $datagridValues) ?
```
Comment (greg0ire) [inline Controller/CategoryAdminController.php]: Avoid negative boolean variables please, it hurts the brain : `$datagridContextIsSet = …`

Comment (ZRazor) [inline Controller/CategoryAdminController.php]: Oh, I did it that way at first, but then changed to avoid `!empty` and `&& ! datagridContextIsSet`

File: Controller/CategoryAdminController.php [hunk 2]
```diff
@@ -40,8 +40,13 @@ public function listAction(Request $request = null)
         }
 
         $datagrid = $this->admin->getDatagrid();
+        $datagridValues = $datagrid->getValues();
 
-        if ($this->admin->getPersistentParameter('context')) {
+        $datagridContextIsSet = array_key_exists('context', $datagridValues) ?
+            !empty($datagridValues['context']['value']) : false;
```
Comment (greg0ire) [inline Controller/CategoryAdminController.php]: Maybe use `isset()` here then. BTW, why not simply use `isset()` directly, without the `array_key_exists` check?

Comment (ZRazor) [inline Controller/CategoryAdminController.php]: We need to handle this situation:
```
'context' => array(
                'value' => ''
            )
```
`isset` will return true, which is not what we want

Comment (greg0ire) [inline Controller/CategoryAdminController.php]: Then maybe `isset($datagridValues['context']['value']) && !empty($datagridValues['context']['value'])` ?

Comment (ZRazor) [inline Controller/CategoryAdminController.php]: Yes, I agree this looks a bit better than `array_key_exists`.
I'll change it.

File: Tests/Controller/CategoryAdminControllerTest.php [hunk 3]
```diff
@@ -337,6 +337,14 @@ public function testListAction($context)
             ->method('getForm')
             ->will($this->returnValue($form));
 
+        $datagrid->expects($this->once())
+            ->method('getValues')
+            ->will($this->returnValue(array(
+                'context' => array(
+                    'value' => $context ? $context : '',
```
Comment (greg0ire) [inline Tests/Controller/CategoryAdminControllerTest.php]: I think you are allowed to use `$context ?: '',` here

Comment (ZRazor) [inline Tests/Controller/CategoryAdminControllerTest.php]: Yes, just copied it from a few lines above
