### PR TITLE
Multiple root categories in context. Fixes #233

### LINKED ISSUE #233: CategoryManager::getCategories fails if multiple categories don't have a parent in the same context
#### Sonata packages

``` bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.6.0           The missing Symfon...
sonata-project/block-bundle              3.1.1           Symfony SonataBloc...
sonata-project/cache                     1.0.7           Cache library
sonata-project/classification-bundle     3.x-dev 626597a Symfony SonataClas...
sonata-project/core-bundle               3.1.1           Symfony SonataCore...
sonata-project/datagrid-bundle           2.2             Symfony SonataData...
sonata-project/doctrine-extensions       1.0.2           Doctrine2 behavior...
sonata-project/doctrine-orm-admin-bundle 3.x-dev 3b7435a Symfony Sonata / I...
sonata-project/easy-extends-bundle       2.1.10          Symfony SonataEasy...
sonata-project/exporter                  1.7.0           Lightweight Export...
sonata-project/intl-bundle               2.2.4           Symfony SonataIntl...
sonata-project/media-bundle              3.x-dev c05ad39 Symfony SonataMedi...
sonata-project/notification-bundle       3.0.0           Symfony SonataNoti...
```
#### Symfony packages

``` bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* func...
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related ...
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5....
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5....
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5....
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7....
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP...
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access...
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.9  The Symfony PHP framework
```
#### PHP version

``` bash
$ php -v
PHP 7.0.10 (cli) (built: Aug 20 2016 10:21:00) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10, Copyright (c) 1999-2016, by Zend Technologies
```
## Subject

Having multiple categories without parent in the same context, if I call `getCategories($context)` method in `CategoryManager` it only returns one category.
## Steps to reproduce

Add more than one category without parent (null) in a context.
Call getCategories for that context.

``` php
$context = ...;
$categoryManager = $this->container->get('sonata.classification.manager.category');
$categories = $categoryManager->getCategories($context);
```
## Expected results

A collection of categories.
## Actual results

Only one category.

I think this code would fix this but I didn't want to create a PR before checking this is actually a bug:

``` php
    /**
     * Load all categories from the database, the current method is very efficient for < 256 categories.
     */
    protected function loadCategories(ContextInterface $context)
    {
        if (array_key_exists($context->getId(), $this->categories)) {
            return;
        }

        $class = $this->getClass();

        $categories = $this->getObjectManager()->createQuery(sprintf('SELECT c FROM %s c WHERE c.context = :context ORDER BY c.parent ASC', $class))
            ->setParameter('context', $context->getId())
            ->execute();

        if (count($categories) == 0) {
            // no category, create one for the provided context
            $category = $this->create();
            $category->setName($context->getName());
            $category->setEnabled(true);
            $category->setContext($context);
            $category->setDescription($context->getName());

            $this->save($category);

            $categories = array($category);
        }

        foreach ($categories as $pos => $category) {
            if (null === $category->getParent()) {
                $root[] = $category;
            }

            $this->categories[$context->getId()][$category->getId()] = $category;

            $parent = $category->getParent();

            $category->disableChildrenLazyLoading();

            if ($parent) {
                $parent->addChild($category);
            }
        }

        $this->categories[$context->getId()] = $root;
    }
```

### PR DESCRIPTION
**Pull request by ZRazor**
I am targetting this branch, because its BC. 

Closes #233

## Changelog

```markdown
### Added
- new methods for root categories in `CategoryManager`

### Fixed
- `CategoryManager::loadCategories` method now loads all root categories in context
- Categories tree now renders all root categories in context

```

## Screenshots

Same db state

## To do

- [x] Add support for multiple root categories in context
- [x] Add more tests for CategoryManager

### CODE REVIEW

**Comment by greg0ire** [comment]
Try to rephrase your changelog as a single entry, directed at users of the bundles (as opposed to developers of the bundle).

File: Controller/CategoryAdminController.php [hunk 1]
```diff
@@ -66,27 +66,33 @@ public function listAction(Request $request = null)
...
+        $rootCategories = $categoryManager->getRootCategoriesSplitByContexts(false);
+
+        // root categories inside the current context
+        $currentCategories = array();
 
         if (!$currentContext && !empty($rootCategories)) {
-            $mainCategory = current($rootCategories);
-            $currentContext = $mainCategory->getContext();
+            $currentCategories = current($rootCategories);
+            $currentContext = $currentCategories[0]->getContext();
```
Comment (greg0ire) [inline Controller/CategoryAdminController.php]: Please use `current` here too, it's less fragile than `[0]`

File: Entity/CategoryManager.php [hunk 2]
```diff
@@ -97,6 +97,32 @@ public function getSubCategoriesPager($categoryId, $page = 1, $limit = 25, $crit
     }
 
     /**
+     * @param CategoryInterface $category
+     *
+     * @return CategoryInterface
+     */
+    public function getRootCategoryWithChildren($category)
```
Comment (greg0ire) [inline Entity/CategoryManager.php]: No type hinting?

Comment (greg0ire) [inline Entity/CategoryManager.php]: Please make methods you introduce final

Comment (ZRazor) [inline Entity/CategoryManager.php]: @greg0ire, One of them is used in tests, and I plan to bring tests for the rest. And PHPUnit cannot mock final methods ;(

Comment (greg0ire) [inline Entity/CategoryManager.php]: Ok… better have tests than final methods I guess. The solution could also be to not mock it, or mock an interface.

File: Controller/CategoryAdminController.php [hunk 3]
```diff
@@ -66,27 +66,33 @@ public function listAction(Request $request = null)
...
+        // all root categories
+        $rootCategories = $categoryManager->getRootCategoriesSplitByContexts(false);
+
+        // root categories inside the current context
+        $currentCategories = array();
 
         if (!$currentContext && !empty($rootCategories)) {
-            $mainCategory = current($rootCategories);
-            $currentContext = $mainCategory->getContext();
+            $currentCategories = current($rootCategories);
```
Comment (core23) [inline Controller/CategoryAdminController.php]: `currentCategories[]`, because `current` will return one item.

Comment (ZRazor) [inline Controller/CategoryAdminController.php]: @core23, mb I need to rename `rootCategories` variable, because it contains array of arrays (categories split by contexts), so `current` will return exactly what we need in this case (array of categories in some context)

**Comment by ZRazor** [comment]
@greg0ire, @core23 
I made all changes and added tests.

**Comment by ZRazor** [comment]
For compatibility with MediaBundle had to keep `CategoryManager::getRootCategories` method as it was, because it is used in `Sonata\MediaBundle\Listener\ORM\MediaEventSubscriber`. Added test for it, to ensure that is works as it should.

File: Entity/CategoryManager.php [hunk 4]
```diff
@@ -136,6 +176,31 @@ public function getRootCategories($loadChildren = true)
     }
 
     /**
+     * @param bool|true $loadChildren
+     *
+     * @return array
+     */
+    public function getRootCategoriesSplitByContexts($loadChildren = true)
```
Comment (core23) [inline Entity/CategoryManager.php]: Should we add this (and the other new public methods) to the `CategoryManagerInterface` with the next major release?

Comment (ZRazor) [inline Entity/CategoryManager.php]: @core23, Yes.
Also we probably need to remove `getRootCategory` and `getRootCategories` methods.
At the current moment they are used in MediaBundle and `AbstractCategoriesBlockService`, so we need them for BC.
I added `@todo NEXT_MAJOR` comments for them.

Comment (ZRazor) [inline Entity/CategoryManager.php]: `getRootCategory` and `getRootCategories ` both return only one root category for the context.
For supporting several root categories I added:

- `getAllRootCategories` - replacement for `getRootCategories`
- `getRootCategoriesSplitByContexts` - for `CategoryAdminController`
- `getRootCategoriesForContext` - replacement for `getRootCategory` in `CategorySelectorType`
- `getRootCategoryWithChildren` - for loading children categories if they are not loaded yet. Also replacement of `getRootCategory`

Comment (core23) [inline Entity/CategoryManager.php]: Can you please add a `NEXT_MAJOR` comment to all new public methods, so we know that we should add them to the interface.

Comment (ZRazor) [inline Entity/CategoryManager.php]: Done

**Comment by greg0ire** [comment]
@core23 please review again

File: Entity/CategoryManager.php [hunk 5]
```diff
@@ -97,6 +97,36 @@ public function getSubCategoriesPager($categoryId, $page = 1, $limit = 25, $crit
     }
 
     /**
+     * NEXT_MAJOR.
```
Comment (core23) [inline Entity/CategoryManager.php]: What should we do with the next major?

Comment (ZRazor) [inline Entity/CategoryManager.php]: I hope this note `NEXT_MAJOR: keep this method.` will be enough, because I dont know what else to add there.

Comment (greg0ire) [inline Entity/CategoryManager.php]: "add this method to the interface"?

Comment (ZRazor) [inline Entity/CategoryManager.php]: Did it, thanks.

**Comment by greg0ire** [comment]
Thanks @ZRazor ! And very nice coverage increase (+4.6% !!!!)

**Comment by enekochan** [comment]
Thanks!

**Comment by enekochan** [comment]
Works like a charm! I've changed my code from this:

```php
$this->om->getRepository('ApplicationSonataClassificationBundle:Category');
$qb = $this->om->createQueryBuilder()
    ->select('c')
    ->from('ApplicationSonataClassificationBundle:Category', 'c')
    ->where('c.parent IS NULL')
    ->andWhere('c.context = :context')
    ->setParameter('context', $business->getContext())
;
$categories = $qb->getQuery()->getResult();
```

To which was my original idea what should have been, this:

```php
$categoryManager = $this->container->get('sonata.classification.manager.category');
$categories = $categoryManager->getCategories($business->getContext());
```

:)

**Comment by OskarStark** [comment]
Thanks for your feedback @enekochan 👍 and thanks @ZRazor for the contribution 🎉

**Comment by OskarStark** [comment]
patch or minor?

**Comment by greg0ire** [comment]
Clearly minor, and the changelog should reflect that.

**Comment by ZRazor** [comment]
@greg0ire do i need to change it?

**Comment by OskarStark** [comment]
nothing todo here for you @ZRazor 👍

**Comment by greg0ire** [comment]
I changed it for you @ZRazor (merged fixed into added)
